version: '3.8'

services:
  tweety-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3004:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: tweety-api
